### ISSUE TITLE
Attempting to test with Vitest

### ISSUE THREAD

**Issue by khill-fbmc** [sombriks/node-libgpiod#18]
I decided to take a stab at getting your tests you wrote to work with [Vitest](https://vitest.dev) since it is the new hotness.

I am getting close but getting this weird error, and since I don't know C++ _I don't know what it means_ heh

![image](https://github.com/sombriks/node-libgpiod/assets/107003416/140735a1-2a32-42ae-a4e5-eb0169616354)

**Comment by sombriks** [comment]
yes it might be related with #4 , at some point i need to go back on the C++ side and see how to solve that.

besides that, going CommonsJS or ES6 modules should not cause any major issue.

that would be a cool enhancement.

**Comment by sombriks** [comment]
this is nice ;-) i have a PR to enable it to run on every commit but as you can imagine we're limited by the lack of gpio pins on github runners 😅 

anyway, please open a PR to the repo when you feel you get a time so we can offer this to everyone consuming this library.

**Comment by sombriks** [comment]
Hi @khill-fbmc !

This is one issue i could address along the 'testing mode' for the library.

In order to proper cover the library with tests, i will need to simulate gpiopins so it can be transparent for the javascript wrapper if we are in a real hardware of inside a github runner or something.

my findings so far point to use exactly what ligpiod itself uses to test: https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/tests/Makefile.am?h=v1.6.x

but we can also make use of some environment variables to override a few things, the operating system environment for instance.

we could create a set of prefixed environment variables to override our system checks, for example `NODE_LIBGPIOD_OS_TYPE` ; lib bootstrap would stilll performing the check, but the env var would take precedence and then we use that.

i plan to spare time this weekend to move forward to it, we can discuss good overrides for this situation and others

**Comment by sombriks** [comment]
still blocked by #24

**Comment by sombriks** [comment]
issues cleanup. 

our mocha test suite still need improvements, vite would be good, if the gpio-sim gets completely figured out on github actions besides local development.

we can back to the topic in the future, focusing on complete API parity for now, we still lack bulk read/write and callbacks.

**Comment by khill-fbmc** [comment]
No worries! I did drive through in classic ADHD style, do some work that was interesting _right then_, and now I am miles away 🙃
